#!/bin/bash
APP_NAME="$(basename "${BASH_SOURCE}" ".sh")"
APP_PATH="$(dirname "$(readlink -f "$0")")"
VENV_PATH="${APP_PATH}/venv"
VENV_PIP="${VENV_PATH}/bin/pip3"
VENV_PYTHON="${VENV_PATH}/bin/python3"
if [ -d "${VENV_PATH}" ] && [ -f "${VENV_PYTHON}" ] ; then
	${VENV_PYTHON} "${APP_PATH}/${APP_NAME}.py" $@
else
	python3 "${APP_PATH}/${APP_NAME}.py" $@
fi
